spring:
  application:
    name: workflow
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=workflow
    username: workflow
    password: workflow
    dbcp2:
      default-schema: workflow
